[package]
name = "app"
version = "0.1.0"
description = "A WalnutBook Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.2", features = [] }
rusqlite = { version = "0.29.0", features = ["bundled", "backup"] }
tauri-plugin-log = "2"
chrono = { version = "0.4", features = ["serde"] }

tauri-dialog = "0.1.1"
dirs = "5.0.1"
open = "5"
base64 = "0.21"


[features]
custom-protocol = ["tauri/custom-protocol"]
